spring.application.name=prueba-accenture

aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-1
aws.dynamodb.table-name=franchise-table
spring.config.import=optional:file:.env[.properties]