spring.application.name=prueba-accenture

aws.credentials.access-key=${AWS_ACCESS_KEY_ID:local}
aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:local}
aws.region=${AWS_REGION:us-east-1}
aws.dynamodb.table-name=${AWS_DYNAMODB_TABLE_NAME:franchise-table}
aws.dynamodb.endpoint=${AWS_DYNAMODB_ENDPOINT:}
spring.config.import=optional:file:.env[.properties]